#ifndef CONSTANTS_HPP
#define CONSTANTS_HPP

enum Constants {
	MSG_SIZE = 512,
	BUFFER_SIZE = 1024,
	PORT_NUMBER_LOWER_BOUND = 1024,
	PORT_NUMBER_UPPER_BOUND = 49152,
	NICKNAME_SIZE = 9
};

#endif // CONSTANTS_HPP